### ISSUE TITLE
UFO support?

### ISSUE THREAD

**Issue by ctrlcctrlv** [silnrsi/graide#9]
Cool project, a few questions.

![graide4_1_rulesMultiple](https://user-images.githubusercontent.com/838783/158139294-0c0105e2-bb14-4f11-85f6-705848e04f22.png)

1. What input font formats are allowed? Is there a possibility to allow UFO? If so I can easily integrate this project into MFEK.
2. Is there an ability to see how OpenType shaping compares to Graphite? Can this editor handle both?
3. Perhaps consider adding screenshot to readme.

**Comment by bobh0303** [comment]
Hi Fredrick, and thanks for taking time to connect with us. To answer your questions:

1. As far as the font format is concerned, at this time only TTF is recognized. Supporting UFO is doable by invoking some form of ufo2ft to create the TTF, though that the dependencies. At this time we are not planning such an enhancement. 
2. Graide handles only Graphite. 
3. Adding a screenshot to the readme is a good idea.  Done.

Regards,
Bob

**Comment by ctrlcctrlv** [comment]
Is the project accepting patches regarding especially ① but also maybe ②?

**Comment by nrsiward** [comment]
We do not intend to put further resources into developing graide at this time. Of course, you're welcome to fork the repo and enhance graide. If so, we may examine what you do and work with you to incorporate some of that work into our repo.
